" ~/.vim/vimrc

call plug#begin()

Plug 'tpope/vim-sensible'

Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-tbone'

Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'itchyny/lightline.vim'

call plug#end()

set viminfofile=~/.vim/viminfo

" Disable the default Vim startup message.
set shortmess+=I

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes. This is to prevent you from
" forgetting about unsaved changes and then quitting e.g. via `:qa!`. We find
" hidden buffers helpful enough to disable this protection. See `:help hidden`
" for more information on this.
set hidden

" This setting makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if
" it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Don't comment on new line
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

set number
set relativenumber

set mouse+=a

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smartindent

set termguicolors
set noshowmode

colorscheme catppuccin_latte
let g:lightline = {
  \ 'colorscheme': 'catppuccin_latte',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
  \ },
  \ 'component_function': {
  \   'gitbranch': 'FugitiveHead'
  \ },
  \ }

set list
set showcmd

set cursorline
set cursorcolumn

let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

let mapleader = " "

nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

vnoremap <leader>y :w !win32yank.exe -i --crlf<CR><CR>
