theme = "catppuccin_latte"

[editor]
auto-info = false
color-modes = true
continue-comments = false
cursorcolumn = true
cursorline = true
line-number = "relative"
true-color = true
# evil = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
rainbow-option = "normal"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "file-modification-indicator"]
right = [
    "selections",
    "position-percentage",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type"
]
